development:
  adapter: mysql2
  encoding: utf8
  database: instagra
  username: root
  host: localhost
  port: 13306
  socket: /opt/boxen/data/socket
production:
  adapter: mysql2
  encoding: utf8
  database: instagra
  username: root
  host: localhost
  password:
test:
  adapter: mysql2
  encoding: utf8
  database: instagra
  username: root
  host: localhost
  password:
