development:
  adapter: mysql2
  encoding: utf8
  database: instagra
  username: root
  host: localhost
  password:
production:
  adapter: mysql2
  encoding: utf8
  database: instagra
  username: root
  host: localhost
  password:
test:
  adapter: mysql2
  encoding: utf8
  database: instagra
  username: root
  host: localhost
  password: